[package]
name = "state-estimation-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.31.1"
ndarray = "0.15.6"
matfile = { version = "0.3.1", features = ["ndarray"] }
